version: "3.7"

networks:
  microservice-net:
    driver: bridge

volumes:
  postgresql_local_data: {}
  postgresql_local_data_backups: {}

services:
  zookeeper:
    image: zookeeper
    container_name: 'keeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - microservice-net
  kafka:
    image: 'bitnami/kafka'
    container_name: 'kafka'
    ports:
      - '9093:9093'
    environment:
      # - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_PROTOCOL:PLAINTEXT
    depends_on:
      - zookeeper
    volumes:
      - /var/tmp/:/bitnami/kafka
    networks:
      - microservice-net

  db:
    image: postgres:11
    volumes:
      - postgresql_local_data:/var/lib/postgresql/data
      - postgresql_local_data_backups:/backups
    environment:
      POSTGRES_PASSWORD: microservice_password
    ports:
      - '5433:5432'
    networks:
      - microservice-net